name: Docker Image CI

on:
  schedule:
    - cron: "0 23 * * 0"

env:
  PROJECT_NAME: readarr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      run: |
        sed "" ./.github/variables/version.var >> $GITHUB_ENV
        NEW_VERSION=$(git ls-remote --tags "https://github.com/Readarr/Readarr/" | cut -d/ -f3- | tail -n1 | tr -d '^{}')
        if [ $CUR_VERSION != $NEW_VERSION ]; then
          docker build . --file Dockerfile --tag nicksica/$PROJECT_NAME:latest
          docker push nicksica/$PROJECT_NAME:latest
          echo CUR_VERSION=$NEW_VERSION > ./github/variables/version.var
        fi
