name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: "0 23 * * 0"
  

env:
  PROJECT_NAME: readarr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Set variables
      run: |
        sed "" ./.github/variables/version.var >> $GITHUB_ENV
    - 
      name: Build the Docker image
      run: |
        NEW_VERSION=$(git ls-remote --tags "https://github.com/Readarr/Readarr/" | cut -d/ -f3- | tail -n1 | tr -d '^{}')
        echo "NEW_VERSION START"
        echo $NEW_VERSION
        echo "NEW_VERSION STOP"
        if [ $CUR_VERSION != $NEW_VERSION ]; then
          #docker build . --file Dockerfile --tag nicksica/$PROJECT_NAME:latest
          #docker push nicksica/$PROJECT_NAME:latest
          echo CUR_VERSION=$NEW_VERSION > ./version.var
          ls -al
          echo "FILE START"
          cat version.var
          echo "FILE STOP"
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          echo "WE ARE HERE"
          git status
          echo "NO WE ARE HERE"
          git add ./version.var
          git commit -m "Update version number"
          git push
        fi
