name: Docker Image CI

on:
  schedule:
    - cron: "0 23 * * 0"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        sed "" ./.github/variables/version.var >> $GITHUB_ENV
        NEW_VERSION=$(git ls-remote --tags "https://github.com/Readarr/Readarr/" | cut -d/ -f3- | tail -n1 | tr -d '^{}')
        if [ $CUR_VERSION != $NEW_VERSION ]; then
          docker build . --file Dockerfile --tag NickSica:readarr:latest
          echo CUR_VERSION=$NEW_VERSION > ./github/variables/version.var
        fi
